openapi: 3.0.0
info:
  title: Square
  description: Use Square APIs to manage and run business including payment, customer,
    product, inventory, and employee management.
  termsOfService: https://connect.squareup.com/tos
  contact:
    name: Square Developer Platform
    url: https://squareup.com/developers
    email: developers@squareup.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "2.0"
  x-server-configuration:
    default-environment: production
    default-server: default
    environments:
      - name: production
        servers:
          - name: default
            url: https://connect.squareup.com
      - name: sandbox
        servers:
          - name: default
            url: https://connect.squareupsandbox.com
      - name: custom
        servers:
          - name: default
            url: '{custom_url}'
  x-square-generic-error-codes:
    - ACCESS_TOKEN_EXPIRED
    - ACCESS_TOKEN_REVOKED
    - API_VERSION_INCOMPATIBLE
    - APPLICATION_DISABLED
    - ARRAY_EMPTY
    - ARRAY_LENGTH_TOO_LONG
    - ARRAY_LENGTH_TOO_SHORT
    - BAD_CERTIFICATE
    - BAD_GATEWAY
    - BAD_REQUEST
    - CONFLICT
    - CONFLICTING_PARAMETERS
    - CURRENCY_MISMATCH
    - EXPECTED_ARRAY
    - EXPECTED_BASE64_ENCODED_BYTE_ARRAY
    - EXPECTED_BOOLEAN
    - EXPECTED_FLOAT
    - EXPECTED_INTEGER
    - EXPECTED_JSON_BODY
    - EXPECTED_MAP
    - EXPECTED_OBJECT
    - EXPECTED_STRING
    - FORBIDDEN
    - GATEWAY_TIMEOUT
    - GONE
    - IDEMPOTENCY_KEY_REUSED
    - INCORRECT_TYPE
    - INSUFFICIENT_SCOPES
    - INTERNAL_SERVER_ERROR
    - INVALID_ARRAY_VALUE
    - INVALID_CONTENT_TYPE
    - INVALID_CURSOR
    - INVALID_ENUM_VALUE
    - INVALID_FORM_VALUE
    - INVALID_SORT_ORDER
    - INVALID_SQUARE_VERSION_FORMAT
    - INVALID_TIME
    - INVALID_TIME_RANGE
    - INVALID_VALUE
    - LOCATION_MISMATCH
    - MAP_KEY_LENGTH_TOO_LONG
    - MAP_KEY_LENGTH_TOO_SHORT
    - MERCHANT_SUBSCRIPTION_NOT_FOUND
    - METHOD_NOT_ALLOWED
    - MISSING_REQUIRED_PARAMETER
    - NOT_ACCEPTABLE
    - NOT_FOUND
    - NOT_IMPLEMENTED
    - NO_FIELDS_SET
    - RATE_LIMITED
    - REQUEST_ENTITY_TOO_LARGE
    - REQUEST_TIMEOUT
    - SANDBOX_NOT_SUPPORTED
    - SERVICE_UNAVAILABLE
    - TOO_MANY_MAP_ENTRIES
    - UNAUTHORIZED
    - UNEXPECTED_VALUE
    - UNKNOWN_BODY_PARAMETER
    - UNKNOWN_QUERY_PARAMETER
    - UNPROCESSABLE_ENTITY
    - UNSUPPORTED_MEDIA_TYPE
    - V1_ACCESS_TOKEN
    - V1_APPLICATION
    - VALUE_EMPTY
    - VALUE_REGEX_MISMATCH
    - VALUE_TOO_HIGH
    - VALUE_TOO_LONG
    - VALUE_TOO_LOW
    - VALUE_TOO_SHORT
servers:
  - url: https://connect.squareup.com
paths:
  /v2/orders/search:
    post:
      tags:
        - Orders
      summary: SearchOrders
      description: |-
        Search all orders for one or more locations. Orders include all sales,
        returns, and exchanges regardless of how or when they entered the Square
        ecosystem (such as Point of Sale, Invoices, and Connect APIs).

        `SearchOrders` requests need to specify which locations to search and define a
        [SearchOrdersQuery](entity:SearchOrdersQuery) object that controls
        how to sort or filter the results. Your `SearchOrdersQuery` can:

          Set filter criteria.
          Set the sort order.
          Determine whether to return results as complete `Order` objects or as
        [OrderEntry](entity:OrderEntry) objects.

        Note that details for orders processed with Square Point of Sale while in
        offline mode might not be transmitted to Square for up to 72 hours. Offline
        orders have a `created_at` value that reflects the time the order was created,
        not the time it was subsequently transmitted to Square.
      operationId: SearchOrders
      security:
        - oauth2:
            - ORDERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 43aa42a4f8fcf3322b75483e78a370f2133aaf14
  /v2/orders:
    post:
      tags:
        - Orders
      summary: CreateOrder
      description: "Creates a new [order](entity:Order) that can include information\
          \ about products for\npurchase and settings to apply to the purchase.\n\n\
          To pay for a created order, see \n[Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders).\n\
          \nYou can modify open orders using the [UpdateOrder](api-endpoint:Orders-UpdateOrder)\
          \ endpoint."
      operationId: CreateOrder
      security:
        - oauth2:
            - ORDERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 43aa42a4f8fcf3322b75483e78a370f2133aaf14
  /v2/orders/{order_id}:
    get:
      tags:
        - Orders
      summary: RetrieveOrder
      description: Retrieves an [Order](entity:Order) by ID.
      operationId: RetrieveOrder
      security:
        - oauth2:
            - ORDERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 43aa42a4f8fcf3322b75483e78a370f2133aaf14
    put:
      tags:
        - Orders
      summary: UpdateOrder
      description: "Updates an open [order](entity:Order) by adding, replacing, or\
          \ deleting\nfields. Orders with a `COMPLETED` or `CANCELED` state cannot be\
          \ updated.\n\nAn `UpdateOrder` request requires the following:\n\n- The `order_id`\
          \ in the endpoint path, identifying the order to update.\n- The latest `version`\
          \ of the order to update.\n- The [sparse order](https://developer.squareup.com/docs/orders-api/manage-orders/update-orders#sparse-order-objects)\n\
          containing only the fields to update and the version to which the update is\n\
          being applied.\n- If deleting fields, the [dot notation paths](https://developer.squareup.com/docs/orders-api/manage-orders#on-dot-notation)\n\
          identifying the fields to clear.\n\nTo pay for an order, see \n[Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders)."
      operationId: UpdateOrder
      security:
        - oauth2:
            - ORDERS_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 43aa42a4f8fcf3322b75483e78a370f2133aaf14
      x-is-sparse-update: true
  /v2/payouts:
    get:
      tags:
        - Payouts
      summary: ListPayouts
      description: "Retrieves a list of all payouts for the default location. \nYou\
          \ can filter payouts by location ID, status, time range, and order them in\
          \ ascending or descending order. \nTo call this endpoint, set `PAYOUTS_READ`\
          \ for the OAuth scope."
      operationId: ListPayouts
      security:
        - oauth2: [ ]
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payouts/payouts-proto/src/main/proto/squareup/payouts/service.proto
      x-proto-sha: 63e5a6095134dbb40e75b7c133622fb29aa6e1e2
  /v2/payouts/{payout_id}:
    get:
      tags:
        - Payouts
      summary: GetPayout
      description: "Retrieves details of a specific payout identified by a payout\
        \ ID. \nTo call this endpoint, set `PAYOUTS_READ` for the OAuth scope."
      operationId: GetPayout
      security:
        - oauth2: [ ]
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payouts/payouts-proto/src/main/proto/squareup/payouts/service.proto
      x-proto-sha: 63e5a6095134dbb40e75b7c133622fb29aa6e1e2
  /v2/refunds:
    get:
      tags:
        - Refunds
      summary: ListPaymentRefunds
      description: |-
        Retrieves a list of refunds for the account making the request.
        
        Results are eventually consistent, and new refunds or changes to refunds might take several
        seconds to appear.
        
        The maximum results per page is 100.
      operationId: ListPaymentRefunds
      security:
        - oauth2:
            - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 495d56e2121254e62dae996ec2126fee007e4ecd
    post:
      tags:
        - Refunds
      summary: RefundPayment
      description: "Refunds a payment. You can refund the entire payment amount or\
          \ a\nportion of it. You can use this endpoint to refund a card payment or\
          \ record a \nrefund of a cash or external payment. For more information, see\n\
          [Refund Payment](https://developer.squareup.com/docs/payments-api/refund-payments)."
      operationId: RefundPayment
      security:
        - oauth2:
            - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 495d56e2121254e62dae996ec2126fee007e4ecd
      x-endpoint-errors:
        - error-code: AMOUNT_TOO_HIGH
        - error-code: CARD_TOKEN_USED
        - error-code: INVALID_CARD
        - error-code: INVALID_CARD_DATA
        - error-code: PAYMENT_NOT_REFUNDABLE
        - error-code: REFUND_AMOUNT_INVALID
        - error-code: REFUND_DECLINED
        - error-code: VERSION_MISMATCH
  /v2/refunds/{refund_id}:
    get:
      tags:
        - Refunds
      summary: GetPaymentRefund
      description: Retrieves a specific refund using the `refund_id`.
      operationId: GetPaymentRefund
      security:
        - oauth2:
            - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 495d56e2121254e62dae996ec2126fee007e4ecd
  /v2/merchants/{merchant_id}:
    get:
      tags:
        - Merchants
      summary: RetrieveMerchant
      description: Retrieves the `Merchant` object for the given `merchant_id`.
      operationId: RetrieveMerchant
      security:
        - oauth2:
            - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /roster/frontend/api/src/main/proto/squareup/roster/frontend/external/merchant.proto
      x-proto-sha: 11ffb68a94888890036e716f133f695e495ad962

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://connect.squareup.com/oauth2/authorize
          tokenUrl: https://connect.squareup.com/oauth2/token
          scopes:
            BANK_ACCOUNTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to bank account information associated with the targeted
              Square account. For example, to call the Connect v1 ListBankAccounts endpoint.
            CASH_DRAWER_READ: |-
              __HTTP Method__: `GET`

              Grants read access to cash drawer shift information. For example, to call the
              ListCashDrawerShifts endpoint.
            CUSTOMERS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to customer information. For example, to call the
              ListCustomers endpoint.
            CUSTOMERS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to customer information. For example, to create and update
              customer profiles.
            DEVICE_CREDENTIAL_MANAGEMENT: |-
              __HTTP Method__: `POST`, `GET`

              Grants read/write access to device credentials information. For example, to
              call the CreateDeviceCode endpoint.
            EMPLOYEES_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee profile information. For example, to call the
              Connect v1 Employees API.
            EMPLOYEES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee profile information. For example, to create
              and modify employee profiles.
            INVENTORY_READ: |-
              __HTTP Method__: `GET`

              Grants read access to inventory information. For example, to call the
              RetrieveInventoryCount endpoint.
            INVENTORY_WRITE: |-
              __HTTP Method__:  `POST`, `PUT`, `DELETE`

              Grants write access to inventory information. For example, to call the
              BatchChangeInventory endpoint.
            ITEMS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to business and location information. For example, to
              obtain a location ID for subsequent activity.
            ITEMS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to product catalog information. For example, to modify or
              add to a product catalog.
            LOYALTY_READ: |-
              __HTTP Method__: `GET`

              Grants read access to loyalty information. For example, to call the
              ListLoyaltyPrograms endpoint.
            LOYALTY_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to loyalty information. For example, to call the
              CreateLoyaltyAccount endpoint.
            MERCHANT_PROFILE_READ: |-
              __HTTP Method__: `GET`

              Grants read access to business and location information. For example, to
              obtain a location ID for subsequent activity.
            ORDERS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to order information. For example, to call the
              BatchRetrieveOrders endpoint.
            ORDERS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to order information. For example, to call the
              CreateCheckout endpoint.
            PAYMENTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to transaction and refund information. For example, to call
              the RetrieveTransaction endpoint.
            PAYMENTS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to transaction and refunds information. For example, to
              process payments with the Payments or Checkout API.
            PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Allow third party applications to deduct a portion of each transaction amount.
              __Required__ to use multiparty transaction functionality with the Payments
              API.
            PAYMENTS_WRITE_IN_PERSON: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to payments and refunds information. For example, to
              process in-person payments.
            SETTLEMENTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to settlement (deposit) information. For example, to call
              the Connect v1 ListSettlements endpoint.
            TIMECARDS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee timecard information. For example, to call the
              Connect v2 SearchShifts endpoint.
            TIMECARDS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee shift information. For example, to create
              and modify employee shifts.
            TIMECARDS_SETTINGS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee timecard settings information. For example, to
              call the GetBreakType endpoint.
            TIMECARDS_SETTINGS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee timecard settings information. For example, to
              call the UpdateBreakType endpoint.
            APPOINTMENTS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to booking information. For example, to call the
              RetrieveBooking endpoint.
            APPOINTMENTS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to booking information. For example, to call the CreateBooking endpoint.
            APPOINTMENTS_BUSINESS_SETTINGS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to booking business settings. For example, to call the
              ListTeamMemberBookingProfiles endpoint.
            INVOICES_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to invoice information. For example, to call the ListInvoices endpoint.
            INVOICES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to invoice information. For example, to call the CreateInvoice endpoint.
            SUBSCRIPTIONS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to subscription information. For example, to call the RetrieveSubscription
              endpoint.
            SUBSCRIPTIONS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to subscription information. For example, to call the CreateSubscription
              endpoint.
            DISPUTES_READ: |-
              __HTTP Method__: `GET`

              Grants read access to dispute information. For example, to call the RetrieveDispute
              endpoint.
            DISPUTES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to dispute information. For example, to call the SubmitEvidence
              endpoint.
            GIFTCARDS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to gift card information. For example, to call the RetrieveGiftCard
              endpoint.
            GIFTCARDS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to gift card information. For example, to call the CreateGiftCard
              endpoint.
            ONLINE_STORE_SNIPPETS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Write access to ECOM online store snippets on published websites.
            ONLINE_STORE_SNIPPETS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Read access to ECOM online store snippets on published websites.
            ONLINE_STORE_SITE_READ: |-
              __HTTP Method__: `GET`, `POST`

              Read access to ECOM online store site details.
            PAYMENTS_WRITE_SHARED_ONFILE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Allows the developer to process payments on behalf of a seller using a shared on file payment method.
            APPOINTMENTS_ALL_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to all of a seller's booking information, calendar, and business details.
              This permission must be accompanied by the `APPOINTMENTS_READ` permission.
            APPOINTMENTS_ALL_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to all booking details, including double-booking a seller.
              This permission must be accompanied by the `APPOINTMENTS_WRITE` permission.
            MERCHANT_PROFILE_WRITE: |-
              __HTTP Method__: `POST`, `PUT`

              Grants write access to business and location information. For example, to create a new location or
              update the business hours at an existing location.
            VENDOR_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to vendor information, for example, when calling the
              `RetrieveVendor` endpoint.
            VENDOR_WRITE: |-
              __HTTP Method__:  `POST`, `PUT`, `DELETE`

              Grants write access to vendor information, for example, when calling the
              `BulkUpdateVendors` endpoint.
            PAYOUTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to payouts and payout entries information. For example,
              to call the Connect v2 `ListPayouts` endpoint.
            RESERVATIONS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to reservation information, for example, when calling the
              `RetrieveReservation` endpoint.
            RESERVATIONS_WRITE: |-
              __HTTP Method__:  `POST`, `PUT`, `DELETE`

              Grants write access to reservation information, for example, when calling the
              `CreateReservation` endpoint.
      x-additional-headers:
        - name: Square-Version
          description: Square Connect API versions
          schema:
            default: 2022-09-21
    oauth2ClientSecret:
      type: apiKey
      name: Authorization
      in: header