// This file was auto-generated by Fern from our API Definition.

package api

type DeleteCustomerRequest struct {
	// The current version of the customer profile.
	//
	// As a best practice, you should include this parameter to enable [optimistic concurrency](https://developer.squareup.com/docs/build-basics/common-api-patterns/optimistic-concurrency) control. For more information, see [Delete a customer profile](https://developer.squareup.com/docs/customers-api/use-the-api/keep-records#delete-customer-profile).
	Version *int64 `json:"-" url:"version,omitempty"`
}

type UpdateCustomerRequest struct {
	// The given name (that is, the first name) associated with the customer profile.
	GivenName *string `json:"given_name,omitempty" url:"-"`
	// The family name (that is, the last name) associated with the customer profile.
	FamilyName *string `json:"family_name,omitempty" url:"-"`
	// A business name associated with the customer profile.
	CompanyName *string `json:"company_name,omitempty" url:"-"`
	// A nickname for the customer profile.
	Nickname *string `json:"nickname,omitempty" url:"-"`
	// The email address associated with the customer profile.
	EmailAddress *string  `json:"email_address,omitempty" url:"-"`
	Address      *Address `json:"address,omitempty" url:"-"`
	// The phone number associated with the customer profile. A phone number can contain 9–16 digits, with an optional `+` prefix.
	PhoneNumber *string `json:"phone_number,omitempty" url:"-"`
	// An optional second ID used to associate the customer profile with an
	// entity in another system.
	ReferenceId *string `json:"reference_id,omitempty" url:"-"`
	// A custom note associated with the customer profile.
	Note *string `json:"note,omitempty" url:"-"`
	// The birthday associated with the customer profile, in RFC 3339 format. The year is optional. The timezone and time are not allowed.
	// For example, `0000-09-21T00:00:00-00:00` represents a birthday on September 21 and `1998-09-21T00:00:00-00:00` represents a birthday on September 21, 1998.
	// You can also specify this value in `YYYY-MM-DD` format.
	Birthday *string `json:"birthday,omitempty" url:"-"`
	// The current version of the customer profile.
	//
	// As a best practice, you should include this field to enable [optimistic concurrency](https://developer.squareup.com/docs/build-basics/common-api-patterns/optimistic-concurrency) control. For more information, see [Update a customer profile](https://developer.squareup.com/docs/customers-api/use-the-api/keep-records#update-a-customer-profile).
	Version *int64          `json:"version,omitempty" url:"-"`
	TaxIds  *CustomerTaxIds `json:"tax_ids,omitempty" url:"-"`
}
