// This file was auto-generated by Fern from our API Definition.

package api

type CreateOrderRequest struct {
	Order *Order `json:"order,omitempty" url:"-"`
	// A value you specify that uniquely identifies this
	// order among orders you have created.
	//
	// If you are unsure whether a particular order was created successfully,
	// you can try it again with the same idempotency key without
	// worrying about creating duplicate orders.
	//
	// For more information, see [Idempotency](https://developer.squareup.com/docs/basics/api101/idempotency).
	IdempotencyKey *string `json:"idempotency_key,omitempty" url:"-"`
}

type SearchOrdersRequest struct {
	// The location IDs for the orders to query. All locations must belong to
	// the same merchant.
	//
	// Min: 1 location ID.
	//
	// Max: 10 location IDs.
	LocationIds []string `json:"location_ids,omitempty" url:"-"`
	// A pagination cursor returned by a previous call to this endpoint.
	// Provide this cursor to retrieve the next set of results for your original query.
	// For more information, see [Pagination](https://developer.squareup.com/docs/basics/api101/pagination).
	Cursor *string            `json:"cursor,omitempty" url:"-"`
	Query  *SearchOrdersQuery `json:"query,omitempty" url:"-"`
	// The maximum number of results to be returned in a single page. It is
	// possible to receive fewer results than the specified limit on a given page.
	//
	// Default: `500`
	Limit *int `json:"limit,omitempty" url:"-"`
	// A Boolean that controls the format of the search results. If `true`,
	// `SearchOrders` returns [OrderEntry](entity:OrderEntry) objects. If `false`, `SearchOrders`
	// returns complete order objects.
	//
	// Default: `false`.
	ReturnEntries *bool `json:"return_entries,omitempty" url:"-"`
}

type UpdateOrderRequest struct {
	Order *Order `json:"order,omitempty" url:"-"`
	// The [dot notation paths](https://developer.squareup.com/docs/orders-api/manage-orders#on-dot-notation)
	// fields to clear. For example, `line_items[uid].note`.
	// For more information, see [Deleting fields](https://developer.squareup.com/docs/orders-api/manage-orders#delete-fields).
	FieldsToClear []string `json:"fields_to_clear,omitempty" url:"-"`
	// A value you specify that uniquely identifies this update request.
	//
	// If you are unsure whether a particular update was applied to an order successfully,
	// you can reattempt it with the same idempotency key without
	// worrying about creating duplicate updates to the order.
	// The latest order version is returned.
	//
	// For more information, see [Idempotency](https://developer.squareup.com/docs/basics/api101/idempotency).
	IdempotencyKey *string `json:"idempotency_key,omitempty" url:"-"`
}
